---
# YAML documents begin with the document separator ---
# The minus in YAML this indicates a list item. The Playbook contains a list
# of plays, with each play being a dictionary

- name: 'Delegating the hosts to the taksk'

  # Target: where our play will run and options it will run with
  hosts: webservers

  # Task: the list of tasks that will be executed within the playbook
  tasks:       
     - name: user creation
       user:
         name: testuser1
         state: present
       notify: show_message
     - name: Running task on localhost
       file:
         path: "/root/ansible.log"
         state: touch
       delegate_to: localhost 
     - name: writing the logs
       lineinfile:
         path: "/root/ansible.log"
         line: 'user testuser1 created sucessfully'
         state: present
       delegate_to: localhost
  handlers:
     - name: show_message
       debug: msg="User created successfully"

# Three dots indicate the end of a YAML document
...
